logging:
  level:
    root: info
    com.example.chapter9: debug
    jdbc:
      sqlonly: off
      sqltiming: off
      resultset: off
      resultsettable: off
      audit: off
      connection: off

spring:
  output.ansi.enabled: ALWAYS
  batch:
    jdbc:
      initialize-schme: always
    job:
      enabled: true
  #      names: ${job.name:NONE} # Program arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행한다.
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch
    driver-class-name: org.mariadb.jdbc.Driver
    # Spring Boot 에서 JDBC 로그
#    url: jdbc:log4jdbc:mariadb://localhost:3306/spring_batch
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: jung0@14
#  sql:
#    init:
#      mode: always # 기본적으로 memory db를 사용하지 않으면 schema.sql을 실행시키지 않습니다. 따라서 다른 db를 사용할 경우 initialization-mode를 설정해줘야 한다.
#      platform: mariadb

  jpa:
    hibernate.naming: # 예제에서는 관습적으로 사용하는 언더스코어 표기법 대신 카멜 표기법을 사용했다.
      implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
      physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
